name: kalorize
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cron: ^0.6.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_animate: ^4.3.0
  get: 4.6.6
  get_storage: ^2.1.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  image_picker: ^1.0.7
  intl: ^0.19.0
  lottie: ^3.1.0
  svg_flutter: ^0.0.1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/img/
    - assets/json/
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/img/logo-app.png"
  remove_alpha_ios: true
